---
- name: Instalar e configurar o Netdata
  hosts: servers
  become: yes

  tasks:
    - name: Baixar e executar o script de instalação do Netdata
      ansible.builtin.shell: curl -Ss 'https://my-netdata.io/kickstart.sh' | bash -s -- --dont-wait
      args:
        creates: /usr/sbin/netdata # Evita rodar o script novamente se já estiver instalado

    - name: Garantir que o diretório health.d existe
      ansible.builtin.file:
        path: /etc/netdata/health.d
        state: directory
        owner: netdata
        group: netdata
        mode: '0755'

    - name: Configurar alerta customizado de CPU (> 80%)
      ansible.builtin.copy:
        dest: /etc/netdata/health.d/cpu_custom.conf
        content: |
          alarm: cpu_usage_custom
          on: system.cpu
          lookup: average -1m unaligned of user,system,softirq,irq,guest
          units: %
          every: 10s
          warn: $this > 80
          crit: $this > 95
          info: Alerta customizado para CPU acima de 80% (media de 1 minuto)
        owner: netdata
        group: netdata
        mode: '0644'
      notify: Reiniciar Netdata

  handlers:
    - name: Reiniciar Netdata
      ansible.builtin.systemd:
        name: netdata
        state: restarted
        enabled: yes